---
- name: TEST PLAYBOOK
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check free disk space using raw module
      raw: echo "DASRA KHADKA " >  dasra1.txt 

    - name: Wait for 180 seconds
      pause:
        seconds: 10

    - name: Display the hostname using raw module
      raw: hostname  
    
